export type WhatsappTemplateLibraryCategory = "UTILITY" | "MARKETING";

export interface WhatsappTemplateLibraryPreset {
  readonly id: string;
  readonly title: string;
  readonly name: string;
  readonly category: WhatsappTemplateLibraryCategory;
  readonly headerText: string;
  readonly bodyText: string;
  readonly footerText: string;
  readonly bodyExamples: readonly string[];
  readonly useCase: string;
}

export const ONEDECORE_WHATSAPP_TEMPLATE_LIBRARY: readonly WhatsappTemplateLibraryPreset[] = [
  {
    id: "new-enquiry",
    title: "New enquiry acknowledgement",
    name: "onedecore_new_enquiry_ack",
    category: "UTILITY",
    headerText: "Enquiry received",
    bodyText: "Hi {{1}}, thank you for contacting ONEDECORE. We have received your {{2}} enquiry. Our team will review it and contact you shortly.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "home interiors"],
    useCase: "Immediate service acknowledgement after an opted-in website enquiry.",
  },
  {
    id: "designer-assigned",
    title: "Designer assigned",
    name: "onedecore_designer_assigned",
    category: "UTILITY",
    headerText: "Your ONEDECORE designer",
    bodyText: "Hi {{1}}, {{2}} has been assigned to your project and will coordinate the next design steps with you.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "Riya"],
    useCase: "Introduce the assigned designer.",
  },
  {
    id: "consultation-confirmed",
    title: "Consultation confirmed",
    name: "onedecore_consultation_confirmed",
    category: "UTILITY",
    headerText: "Consultation confirmed",
    bodyText: "Hi {{1}}, your ONEDECORE consultation is confirmed for {{2}}. We look forward to discussing your requirements.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "28 Sep, 11:00 AM"],
    useCase: "Confirmation after a consultation is scheduled.",
  },
  {
    id: "consultation-reminder",
    title: "Consultation reminder",
    name: "onedecore_consultation_reminder",
    category: "UTILITY",
    headerText: "Consultation reminder",
    bodyText: "Hi {{1}}, a reminder that your ONEDECORE consultation is scheduled for {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "tomorrow at 11:00 AM"],
    useCase: "Appointment reminder.",
  },
  {
    id: "site-visit-confirmed",
    title: "Site visit confirmed",
    name: "onedecore_site_visit_confirmed",
    category: "UTILITY",
    headerText: "Site visit confirmed",
    bodyText: "Hi {{1}}, your ONEDECORE site visit is confirmed for {{2}}. Our team member {{3}} will coordinate with you.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "30 Sep, 3:00 PM", "Rohan"],
    useCase: "Site-visit confirmation.",
  },
  {
    id: "site-visit-reminder",
    title: "Site visit reminder",
    name: "onedecore_site_visit_reminder",
    category: "UTILITY",
    headerText: "Site visit reminder",
    bodyText: "Hi {{1}}, this is a reminder for your ONEDECORE site visit on {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "tomorrow at 3:00 PM"],
    useCase: "Site-visit reminder.",
  },
  {
    id: "site-visit-completed",
    title: "Site visit completed",
    name: "onedecore_site_visit_completed",
    category: "UTILITY",
    headerText: "Site visit completed",
    bodyText: "Hi {{1}}, your site visit has been completed. Our team is now working on the next step: {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "design development"],
    useCase: "Post-visit status update.",
  },
  {
    id: "design-ready",
    title: "Design ready",
    name: "onedecore_design_ready",
    category: "UTILITY",
    headerText: "Your design is ready",
    bodyText: "Hi {{1}}, your ONEDECORE design is ready for review. Your designer will coordinate the review with you.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Design milestone notification.",
  },
  {
    id: "quotation-ready",
    title: "Quotation ready",
    name: "onedecore_quotation_ready",
    category: "UTILITY",
    headerText: "Quotation ready",
    bodyText: "Hi {{1}}, your ONEDECORE quotation {{2}} is ready. Our team will take you through the scope and commercial details.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "OD-Q-1024"],
    useCase: "Quotation availability notification.",
  },
  {
    id: "quotation-follow-up",
    title: "Quotation follow-up",
    name: "onedecore_quotation_follow_up",
    category: "UTILITY",
    headerText: "Quotation follow-up",
    bodyText: "Hi {{1}}, we are following up on quotation {{2}}. Please let us know if you would like us to clarify any part of the proposed scope.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "OD-Q-1024"],
    useCase: "Service follow-up on an existing quotation.",
  },
  {
    id: "consultation-reschedule",
    title: "Consultation reschedule",
    name: "onedecore_consultation_rescheduled",
    category: "UTILITY",
    headerText: "Consultation rescheduled",
    bodyText: "Hi {{1}}, your ONEDECORE consultation has been rescheduled to {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "2 Oct, 4:00 PM"],
    useCase: "Rescheduled appointment update.",
  },
  {
    id: "project-update",
    title: "Project update",
    name: "onedecore_project_update",
    category: "UTILITY",
    headerText: "Project update",
    bodyText: "Hi {{1}}, an update on your ONEDECORE project: {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "the design review has been completed"],
    useCase: "General project milestone communication.",
  },
  {
    id: "payment-reminder",
    title: "Payment reminder",
    name: "onedecore_payment_reminder",
    category: "UTILITY",
    headerText: "Payment reminder",
    bodyText: "Hi {{1}}, this is a reminder regarding the payment milestone for your ONEDECORE project, due on {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "5 Oct 2026"],
    useCase: "Existing-project payment reminder.",
  },
  {
    id: "installation-scheduled",
    title: "Installation scheduled",
    name: "onedecore_installation_scheduled",
    category: "UTILITY",
    headerText: "Installation scheduled",
    bodyText: "Hi {{1}}, installation for your ONEDECORE project is scheduled to begin on {{2}}.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "10 Oct 2026"],
    useCase: "Installation schedule notification.",
  },
  {
    id: "project-handover",
    title: "Project handover",
    name: "onedecore_project_handover",
    category: "UTILITY",
    headerText: "Project handover",
    bodyText: "Hi {{1}}, your ONEDECORE project is ready for handover on {{2}}. Our team will coordinate the final walkthrough.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha", "20 Oct 2026"],
    useCase: "Handover coordination.",
  },
  {
    id: "feedback-request",
    title: "Feedback request",
    name: "onedecore_feedback_request",
    category: "UTILITY",
    headerText: "How was your experience?",
    bodyText: "Hi {{1}}, thank you for choosing ONEDECORE. We would value your feedback on your recently completed project.",
    footerText: "ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Post-service feedback request.",
  },
  {
    id: "marketing-complete-home",
    title: "Complete Home Interiors",
    name: "onedecore_complete_home_interiors",
    category: "MARKETING",
    headerText: "Complete Home Interiors",
    bodyText: "Hi {{1}}, planning your home interiors? ONEDECORE can help you plan design, materials and execution in one coordinated journey.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Consented complete-home-interiors campaign.",
  },
  {
    id: "marketing-kitchen",
    title: "Modular Kitchen",
    name: "onedecore_modular_kitchen",
    category: "MARKETING",
    headerText: "Modular Kitchens",
    bodyText: "Hi {{1}}, explore a modular kitchen planned around your space, storage needs and preferred finishes with ONEDECORE.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Consented modular-kitchen campaign.",
  },
  {
    id: "marketing-wardrobes",
    title: "Wardrobes",
    name: "onedecore_wardrobes",
    category: "MARKETING",
    headerText: "Custom Wardrobes",
    bodyText: "Hi {{1}}, explore ONEDECORE wardrobe solutions planned around your room, storage and finish preferences.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Consented wardrobe campaign.",
  },
  {
    id: "marketing-renovation",
    title: "Renovation",
    name: "onedecore_renovation",
    category: "MARKETING",
    headerText: "Planning a renovation?",
    bodyText: "Hi {{1}}, if you are considering a home renovation, ONEDECORE can help plan the scope, design and execution.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Consented renovation campaign.",
  },
  {
    id: "marketing-free-consultation",
    title: "Free 3D Design Consultation",
    name: "onedecore_free_design_consultation",
    category: "MARKETING",
    headerText: "Design consultation",
    bodyText: "Hi {{1}}, book a ONEDECORE design consultation to discuss your space, requirements and next steps.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Consented consultation campaign.",
  },
  {
    id: "marketing-reengagement",
    title: "Dormant lead re-engagement",
    name: "onedecore_lead_reengagement",
    category: "MARKETING",
    headerText: "Still planning your interiors?",
    bodyText: "Hi {{1}}, if your interior plans are still active, ONEDECORE would be happy to help you restart the conversation.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha"],
    useCase: "Consented dormant-lead re-engagement.",
  },
  {
    id: "marketing-limited-period",
    title: "Limited-period consultation",
    name: "onedecore_limited_period_consultation",
    category: "MARKETING",
    headerText: "Consultation availability",
    bodyText: "Hi {{1}}, ONEDECORE has limited consultation slots available during {{2}}. Reply if you would like our team to contact you.",
    footerText: "Marketing message · ONEDECORE",
    bodyExamples: ["Asha", "October"],
    useCase: "Consented seasonal or limited-period campaign.",
  },
] as const;

export function getWhatsappTemplateLibraryPreset(
  id: string | null | undefined
): WhatsappTemplateLibraryPreset | null {
  return ONEDECORE_WHATSAPP_TEMPLATE_LIBRARY.find((preset) => preset.id === id) ?? null;
}
