export interface PuneAreaSeo {
  readonly slug: string;
  readonly name: string;
  readonly zone: string;
  readonly context: string;
  readonly planning: string;
  readonly nearby: readonly string[];
}

export const PUNE_AREA_PAGES: readonly PuneAreaSeo[] = [
  { slug:"baner", name:"Baner", zone:"west Pune", context:"Apartments and established residential pockets in Baner can call for very different interior scopes, from new-home fit-outs to selective upgrades.", planning:"Start by mapping fixed site conditions, storage needs and the rooms that need custom work before selecting finishes.", nearby:["Balewadi","Aundh","Pashan"] },
  { slug:"balewadi", name:"Balewadi", zone:"west Pune", context:"Balewadi has a mix of newer apartment communities and lived-in homes, so interior planning should begin with the actual handover or existing-site condition.", planning:"Coordinate kitchen, wardrobes and living-room storage as one specification so repeated finishes and hardware stay consistent.", nearby:["Baner","Wakad","Pimple Saudagar"] },
  { slug:"aundh", name:"Aundh", zone:"west Pune", context:"Aundh includes both established homes and apartment developments where renovation constraints can matter as much as the new interior design.", planning:"Measure existing services and site constraints early when the scope includes civil, electrical or ceiling changes.", nearby:["Baner","Pashan","Kothrud"] },
  { slug:"pashan", name:"Pashan", zone:"west Pune", context:"Homes around Pashan vary in age and layout, making measured site planning important before cabinetry or renovation decisions are locked.", planning:"Treat circulation, storage depth and existing walls as design inputs rather than relying on a standard apartment template.", nearby:["Baner","Aundh","Sus Road"] },
  { slug:"sus-road", name:"Sus Road", zone:"west Pune", context:"Residential growth around Sus Road includes many apartment interiors where efficient storage and coordinated room finishes are common priorities.", planning:"Plan high-use storage first—kitchen, wardrobes and living-room units—then coordinate the supporting finishes.", nearby:["Baner","Pashan","Balewadi"] },
  { slug:"wakad", name:"Wakad", zone:"Pimpri-Chinchwad and west Pune", context:"Wakad's apartment-heavy residential market makes complete-home coordination useful when several rooms need modular storage at the same time.", planning:"Freeze room-by-room storage requirements before final material selection to reduce late changes across the home.", nearby:["Tathawade","Punawale","Balewadi"] },
  { slug:"hinjewadi", name:"Hinjewadi", zone:"west Pune", context:"Homes around Hinjewadi often sit within newer residential developments, where the base apartment condition can simplify some work while still requiring detailed storage planning.", planning:"Use the handover condition and builder provisions as the starting point for kitchen, wardrobe and electrical planning.", nearby:["Wakad","Tathawade","Baner"] },
  { slug:"tathawade", name:"Tathawade", zone:"Pimpri-Chinchwad", context:"Tathawade's newer apartment inventory makes early interior planning useful for owners preparing around possession and move-in.", planning:"Document appliance positions, wardrobe requirements and any builder-provided finishes before finalizing the interior scope.", nearby:["Wakad","Punawale","Ravet"] },
  { slug:"punawale", name:"Punawale", zone:"Pimpri-Chinchwad", context:"Punawale includes growing apartment communities where practical storage and move-in coordination can shape the interior brief.", planning:"Prioritize kitchen utility, bedroom storage and living-room functions before decorative layers are selected.", nearby:["Tathawade","Ravet","Wakad"] },
  { slug:"ravet", name:"Ravet", zone:"Pimpri-Chinchwad", context:"Ravet's residential developments include many new-home interior opportunities where a clear room-by-room scope helps control decisions.", planning:"Separate must-have storage and functional work from optional decorative upgrades before comparing specifications.", nearby:["Punawale","Tathawade","Wakad"] },
  { slug:"pimple-saudagar", name:"Pimple Saudagar", zone:"Pimpri-Chinchwad", context:"Pimple Saudagar has both established and newer apartments, so projects can range from fresh interiors to renovation-led upgrades.", planning:"Confirm what can be retained before demolition or replacement is included in a renovation scope.", nearby:["Wakad","Balewadi","Aundh"] },
  { slug:"kharadi", name:"Kharadi", zone:"east Pune", context:"Kharadi has a large concentration of apartment communities, making complete-home, kitchen and wardrobe planning relevant across both new and occupied homes.", planning:"Coordinate storage, appliance planning and electrical points early when several modular scopes are being delivered together.", nearby:["Wagholi","Viman Nagar","Kalyani Nagar"] },
  { slug:"viman-nagar", name:"Viman Nagar", zone:"east Pune", context:"Viman Nagar combines established apartments with premium residential pockets where site-specific space planning matters more than a generic design package.", planning:"Measure circulation and usable wall lengths carefully before committing to full-height storage or large living-room units.", nearby:["Kalyani Nagar","Kharadi","Wagholi"] },
  { slug:"kalyani-nagar", name:"Kalyani Nagar", zone:"east Pune", context:"Kalyani Nagar homes can involve premium finishes, existing-home upgrades or complete interior scopes depending on the property and its condition.", planning:"Resolve the functional plan and retained elements first so finish upgrades are applied to a coherent scope.", nearby:["Viman Nagar","Koregaon Park","Kharadi"] },
  { slug:"koregaon-park", name:"Koregaon Park", zone:"central-east Pune", context:"Koregaon Park includes distinctive apartments and older properties where renovation and custom detailing may require more site-led planning.", planning:"Survey existing walls, services and retained finishes before design development when working in an older property.", nearby:["Kalyani Nagar","Viman Nagar","Hadapsar"] },
  { slug:"wagholi", name:"Wagholi", zone:"east Pune", context:"Wagholi's expanding residential market includes many new apartments where complete-home interiors can be planned before move-in.", planning:"Use possession drawings and an on-site measurement check together before manufacturing dimensions are frozen.", nearby:["Kharadi","Viman Nagar","Hadapsar"] },
  { slug:"hadapsar", name:"Hadapsar", zone:"east Pune", context:"Hadapsar spans established neighborhoods and large apartment communities, so interior requirements can vary from modular additions to full renovation.", planning:"Define whether the project is a fresh fit-out or a renovation first, because site work changes sequencing and budget structure.", nearby:["Magarpatta","Wanowrie","Kharadi"] },
  { slug:"magarpatta", name:"Magarpatta", zone:"east Pune", context:"Apartment homes around Magarpatta often benefit from coordinated storage planning across kitchens, bedrooms and living areas.", planning:"Create one material and hardware schedule across repeated cabinetry to keep the home visually and technically consistent.", nearby:["Hadapsar","Kharadi","Wanowrie"] },
  { slug:"kothrud", name:"Kothrud", zone:"west-central Pune", context:"Kothrud has a broad mix of established housing and newer redevelopment, creating both renovation and complete-interior requirements.", planning:"For existing homes, identify retained flooring, doors, electrical points and plumbing before new cabinetry is detailed.", nearby:["Aundh","Pashan","Ambegaon"] },
  { slug:"undri", name:"Undri", zone:"south Pune", context:"Undri's residential developments include apartment and larger-home formats where storage requirements can differ significantly by property.", planning:"Plan storage volume and room priorities from the household's actual needs rather than copying a standard BHK package.", nearby:["NIBM","Kondhwa","Wanowrie"] },
  { slug:"nibm", name:"NIBM", zone:"south Pune", context:"The NIBM area includes apartments and premium residential developments where complete-home scopes often need careful finish coordination.", planning:"Build a finish palette after the room functions and storage elevations are resolved, not before.", nearby:["Kondhwa","Undri","Wanowrie"] },
  { slug:"kondhwa", name:"Kondhwa", zone:"south Pune", context:"Kondhwa's varied housing stock means interior projects can involve new modular work, complete interiors or renovation of existing rooms.", planning:"A site survey should determine what is retained, replaced or modified before the project scope is priced.", nearby:["NIBM","Undri","Wanowrie"] },
  { slug:"wanowrie", name:"Wanowrie", zone:"south-east Pune", context:"Wanowrie includes established residential properties where renovation planning and made-to-fit storage can be especially relevant.", planning:"Check existing services and usable wall conditions before designing cabinetry around an occupied or older home.", nearby:["NIBM","Hadapsar","Kondhwa"] },
  { slug:"dhanori", name:"Dhanori", zone:"north-east Pune", context:"Dhanori's apartment developments create opportunities for practical complete-home interiors focused on storage, kitchens and move-in readiness.", planning:"Resolve appliance sizes and bedroom storage needs before cabinetry drawings are finalized.", nearby:["Vishrantwadi","Viman Nagar","Wagholi"] },
  { slug:"vishrantwadi", name:"Vishrantwadi", zone:"north-east Pune", context:"Vishrantwadi combines established housing with apartment developments, so the right interior scope depends heavily on existing site condition.", planning:"Separate renovation work from new modular work in the brief so execution dependencies are clear.", nearby:["Dhanori","Viman Nagar","Kalyani Nagar"] },
  { slug:"ambegaon", name:"Ambegaon", zone:"south-west Pune", context:"Ambegaon includes growing residential pockets where new-home interior planning can focus on efficient storage and coordinated execution.", planning:"Start with high-use rooms and fixed requirements, then layer optional design features into the specification.", nearby:["Kothrud","Undri","Kondhwa"] }
] as const;

export function getPuneArea(slug: string) { return PUNE_AREA_PAGES.find((area) => area.slug === slug); }
