/**
 * Phase 3A1 — personal data inventory.
 * Separates current operational truth from future planned processing.
 */

export type DataInventoryTiming = "current" | "future" | "current-and-future";

export type DataRiskLevel = "low" | "medium" | "high";

export interface DataInventoryEntry {
  readonly category: string;
  readonly currentOrFuture: DataInventoryTiming;
  readonly source: string;
  readonly purpose: string;
  readonly required: boolean;
  readonly legalGround: string;
  readonly system: string;
  readonly processor: string;
  readonly accessRole: string;
  readonly retentionDecision: "OWNER_DECISION_REQUIRED";
  readonly deletionTrigger: string;
  readonly risk: DataRiskLevel;
  readonly accuracyRequirement: string;
  readonly ownerDecision: string;
  readonly currentTruth: string;
}

export const DATA_INVENTORY_CURRENT_TRUTH: readonly string[] = [
  "The homepage planner and estimator run in-browser only.",
  "Copied brief text is not submitted to any backend.",
  "No contact or lead store exists from the current homepage.",
  "WhatsApp integration is not live.",
  "Groq AI processing is not live.",
  "No campaign data is collected.",
  "No payment-card or payment data is processed.",
] as const;

export const DATA_INVENTORY: readonly DataInventoryEntry[] = [
  {
    category: "contact-identity",
    currentOrFuture: "future",
    source: "Future enquiry forms, CRM, phone, email, WhatsApp",
    purpose: "Identify and respond to individuals requesting interior services",
    required: true,
    legalGround: "Consent and/or contract — pending legal-counsel review",
    system: "Future CRM / enquiry backend",
    processor: "Planned — not active",
    accessRole: "Owner-approved operational roles only",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Purpose end, withdrawal, or lawful retention expiry — pending owner decision",
    risk: "medium",
    accuracyRequirement: "Contact details must be kept accurate on request",
    ownerDecision: "Retention period and lawful ground pending",
    currentTruth: "No contact data is collected or stored from the current homepage.",
  },
  {
    category: "property-requirements",
    currentOrFuture: "current-and-future",
    source: "In-browser planner; future submitted enquiries",
    purpose: "Understand property type, rooms, services and design requirements",
    required: false,
    legalGround: "Consent — pending legal-counsel review",
    system: "Browser memory (current); future backend",
    processor: "None (current)",
    accessRole: "Browser user (current); future authorised staff",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Browser session end (current); purpose end (future) — pending owner decision",
    risk: "low",
    accuracyRequirement: "User-supplied; correction on request when stored",
    ownerDecision: "Future retention pending",
    currentTruth: "Planner inputs remain in-browser; copied brief is not submitted.",
  },
  {
    category: "estimate-budget",
    currentOrFuture: "current-and-future",
    source: "In-browser estimator; future submitted enquiries",
    purpose: "Provide indicative planning ranges and future quotation preparation",
    required: false,
    legalGround: "Consent — pending legal-counsel review",
    system: "Browser memory (current); future backend",
    processor: "None (current)",
    accessRole: "Browser user (current); future authorised staff",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Browser session end (current); purpose end (future)",
    risk: "low",
    accuracyRequirement: "Indicative only; not a quotation",
    ownerDecision: "Future retention pending",
    currentTruth: "Estimator outputs are indicative planning guidance only; not submitted.",
  },
  {
    category: "consent",
    currentOrFuture: "future",
    source: "Future forms and communication opt-in flows",
    purpose: "Record lawful basis, purpose-specific consent and withdrawal evidence",
    required: true,
    legalGround: "DPDP consent requirements — pending operational implementation",
    system: "Future consent store",
    processor: "Planned — not active",
    accessRole: "Privacy/admin roles",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Withdrawal plus lawful evidence retention — pending owner decision",
    risk: "medium",
    accuracyRequirement: "Consent records must reflect exact copy version shown",
    ownerDecision: "Retention and evidence format pending",
    currentTruth: "No consent records are captured on the current website.",
  },
  {
    category: "messages",
    currentOrFuture: "future",
    source: "Future email, phone, WhatsApp, in-person notes",
    purpose: "Service communication and enquiry handling",
    required: false,
    legalGround: "Consent and/or contract — pending legal-counsel review",
    system: "Future CRM / messaging integrations",
    processor: "Planned Meta WhatsApp, email/SMS — not active",
    accessRole: "Authorised operational staff",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Purpose end or erasure request — pending owner decision",
    risk: "medium",
    accuracyRequirement: "Operational accuracy; correction on request",
    ownerDecision: "Channel retention pending",
    currentTruth: "No message store from homepage interactions.",
  },
  {
    category: "media",
    currentOrFuture: "current-and-future",
    source: "Portfolio CMS (published items); future client uploads",
    purpose: "Showcase completed work; future client-provided reference media",
    required: false,
    legalGround: "Legitimate use / consent for client media — pending review",
    system: "Supabase storage (Portfolio); future upload flows",
    processor: "Supabase (current Portfolio only)",
    accessRole: "Admin CMS; future client with consent",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Unpublish, consent withdrawal or project end — pending owner decision",
    risk: "medium",
    accuracyRequirement: "Portfolio items must reflect authentic ONEDECORE work when published",
    ownerDecision: "Client media consent and retention pending",
    currentTruth: "Portfolio uses existing CMS; homepage project proof mode is pending.",
  },
  {
    category: "campaign-data",
    currentOrFuture: "future",
    source: "Future marketing campaigns and UTM tracking",
    purpose: "Measure campaign performance and optional marketing communication",
    required: false,
    legalGround: "Consent — pending",
    system: "Future campaign engine / analytics",
    processor: "Planned analytics — not active",
    accessRole: "Marketing/admin roles",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Campaign end or opt-out — pending owner decision",
    risk: "medium",
    accuracyRequirement: "Attribution accuracy when implemented",
    ownerDecision: "Campaign categories and retention pending",
    currentTruth: "No campaign engine or campaign data on current website.",
  },
  {
    category: "ai-runs-summaries",
    currentOrFuture: "future",
    source: "Future Groq AI consultation assistant",
    purpose: "Draft or assist service responses; operational summaries",
    required: false,
    legalGround: "Consent and disclosure — pending",
    system: "Future AI integration",
    processor: "Planned Groq — not active",
    accessRole: "Authorised staff; human review required",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Purpose end or erasure — pending owner decision",
    risk: "high",
    accuracyRequirement: "Human review; no automated legal/financial decisions",
    ownerDecision: "AI retention and logging pending",
    currentTruth: "Groq processing is not live.",
  },
  {
    category: "consultation-proposal-project",
    currentOrFuture: "future",
    source: "Future CRM, site visits, quotations, project delivery",
    purpose: "Consultation scheduling, proposals, contracts and project coordination",
    required: false,
    legalGround: "Contract and consent — pending",
    system: "Future CRM / project systems",
    processor: "Planned — not active",
    accessRole: "Authorised operational and delivery staff",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Project completion plus lawful retention — pending owner decision",
    risk: "high",
    accuracyRequirement: "Contractual and operational accuracy",
    ownerDecision: "Full CRM retention schedule pending",
    currentTruth: "No consultation is booked or submitted from current website.",
  },
  {
    category: "logs",
    currentOrFuture: "current-and-future",
    source: "Hosting, Supabase auth, application and security logs",
    purpose: "Security, audit, troubleshooting and access control",
    required: true,
    legalGround: "Legitimate security interest — pending legal-counsel review",
    system: "Supabase; hosting infrastructure",
    processor: "Supabase (current)",
    accessRole: "Restricted admin / infrastructure",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Retention expiry or anonymisation — pending owner decision",
    risk: "medium",
    accuracyRequirement: "Integrity for security investigation",
    ownerDecision: "Log retention periods pending",
    currentTruth: "Existing Supabase auth and Portfolio admin access logs only.",
  },
  {
    category: "device-network",
    currentOrFuture: "future",
    source: "Future backend request handling",
    purpose: "Fraud prevention, security and service delivery",
    required: false,
    legalGround: "Legitimate interest — pending review",
    system: "Future backend / CDN",
    processor: "Hosting provider when verified",
    accessRole: "Infrastructure / security",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Short retention or anonymisation — pending owner decision",
    risk: "low",
    accuracyRequirement: "Minimal collection; no fingerprinting",
    ownerDecision: "Collection scope pending",
    currentTruth: "No backend capture of device/network data from homepage planner.",
  },
  {
    category: "cookies",
    currentOrFuture: "current",
    source: "Essential framework and auth storage only",
    purpose: "Session, authentication and essential site operation",
    required: true,
    legalGround: "Essential operation",
    system: "Browser; Supabase auth cookies for admin",
    processor: "Supabase (auth only)",
    accessRole: "User browser; admin sessions",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Session end or logout",
    risk: "low",
    accuracyRequirement: "Essential only",
    ownerDecision: "Future tracking cookie review separate",
    currentTruth: "No analytics, Meta Pixel, advertising cookies or fingerprinting approved.",
  },
  {
    category: "payment-data",
    currentOrFuture: "future",
    source: "Future payment flows if implemented",
    purpose: "Process payments for services or deposits",
    required: false,
    legalGround: "Contract and regulatory requirements — pending",
    system: "Future payment gateway",
    processor: "Planned — not active",
    accessRole: "Finance / authorised roles",
    retentionDecision: "OWNER_DECISION_REQUIRED",
    deletionTrigger: "Statutory and contractual retention — pending owner decision",
    risk: "high",
    accuracyRequirement: "PCI and tax compliance when implemented",
    ownerDecision: "Payment processor and retention pending",
    currentTruth: "No payment-card or payment data is planned or processed now.",
  },
] as const;
